name: Self-test
on:
  workflow_dispatch: {}
  pull_request: {}
  push: {}

jobs:
  self-test:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: true
    steps:
      - uses: actions/checkout@v4
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2.3.0

      - uses: ./
        id: provider-version
        with:
          set-env: "PROVIDER_VERSION"

      - name: Print outputs
        run: 'echo "Step: ${{ steps.provider-version.outputs.version }}, Environment: ${PROVIDER_VERSION}"'

      - if: steps.provider-version.outputs.version != env.PROVIDER_VERSION
        run: |
          echo "Version does not match expected value"
          exit 1
        continue-on-error: true

      - run: npm ci
      - run: npm test
      - run: npm run build

      - name: Check git status
        uses: pulumi/git-status-check-action@v1
